dist: trusty
sudo: required

language: elixir
elixir:
  - 1.5
otp_release:
  - 18.0

matrix:
  include:
    - elixir: 1.5
      otp_release: 20.0

addons:
  postgresql: '9.4'

services:
  - postgresql

before_install:
  - wget http://emqtt.io/downloads/stable/ubuntu14_04-deb -O emqtt.deb
  - sudo dpkg -i emqtt.deb
  - sudo service emqttd start

before_script:
  - mix do ecto.create, ecto.migrate

env:
  - MIX_ENV=test

script:
- mix coveralls.travis
