language: elixir

elixir:
  - 1.4.5

addons:
  postgresql: '9.4'

services:
  - postgresql

before_install:
  - wget http://emqtt.com/downloads/latest/ubuntu16_04
  - mv ubuntu16_04 latest_emqtt.deb
  - sudo dpkg -i latest_emqtt.deb
  - sudo service emqttd start

before_script:
  - mix do ecto.create, ecto.migrate

env:
  - MIX_ENV=test

script:
- mix coveralls.travis
